### ISSUE TITLE
Error in Dialog/visualize_result.py

### ISSUE THREAD

**Issue by prayalankar2** [seominjoon/qrn#1]
When I try to  visualize the result of Dialog dataset after training I get the following error.
Traceback (most recent call last):
  File "/home/prayalankar/anaconda3/envs/tyu/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/prayalankar/anaconda3/envs/tyu/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/prayalankar/qrn/dialog/visualize_result.py", line 174, in <module>
    list_results(ARGS)
  File "/home/prayalankar/qrn/dialog/visualize_result.py", line 88, in list_results
    X, Q, Y, Y1, Y2, Y3, Y4, Y5, Y6, Y7 = data[:10]
ValueError: not enough values to unpack (expected 10, got 4)

**Comment by shmsw25** [comment]
@prayalankar2 
Sorry for the inconvenience.
There was a bug in the code and it is fixed now.
Thanks!
