### ISSUE TITLE
Unsupported operand

### ISSUE THREAD

**Issue by AniketRaj172** [seominjoon/qrn#11]
Config ID <absl.flags._flag.Flag object at 0x7f3fcc0c47b8>, task <absl.flags._flag.Flag object at 0x7f3fcc0c42b0>, 1 trials
Traceback (most recent call last):
  File "/home/aniket/anaconda3/envs/py305/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/aniket/anaconda3/envs/py305/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aniket/qrn/babi/main.py", line 272, in <module>
    tf.app.run()
  File "/home/aniket/anaconda3/envs/py305/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/aniket/qrn/babi/main.py", line 181, in main
    summary = _main(config, num_trials)
  File "/home/aniket/qrn/babi/main.py", line 191, in _main
    load_metadata(config)
  File "/home/aniket/qrn/babi/main.py", line 135, in load_metadata
    data_dir = os.path.join(config.data_dir, config.lang + ("-10k" if config.large else ""))
TypeError: unsupported operand type(s) for +: 'Flag' and 'str'

How to solve this error? Please help me.

**Comment by santiontanon** [comment]
I just checked this repo out and having the same issue. Any clues?
